[package]
name = "firehose-pb"
version = "0.1.0"

[[bin]]
name = "firehose-pb"
path = "src/main.rs"

[dependencies]
prost = "0.9"
prost-types = "0.9"
tonic = "0.5.0"
tonic-build = "0.5.0"
num-traits = "0.2"

[build-dependencies]
